### ISSUE TITLE
Prioritize Maintenanced version of packages

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/web#100]
It would be ideal to return the "highest most up to date version"

Gtest report an unmainted version as "latest" (see my note below for theory) this is in both the search and main page and requires extra clicks to find the correct page

![image](https://github.com/conan-io/web/assets/16867443/8df138e1-01be-425e-a551-95b17edd9eb6)

![image](https://github.com/conan-io/web/assets/16867443/3f399acf-1576-4945-a264-4fd6533646e9)

***

I noticed something funky, this package has a much older cci.yyyymmdd syntax and this seems to bug up the version ranges
For example: gtest/[>=1.14, <2] give me ERROR: Missing prebuilt package for 'gtest/cci.20210126'
I am see the same thing in the UI

Are these related?

**Comment by davidsanfal** [comment]
Feature deployed. Now we show maintained version first.

<img width="1278" alt="Screenshot 2023-09-04 at 14 14 39" src="https://github.com/conan-io/web/assets/5907894/e022259e-aa67-4d7f-a7a0-3a7a4c06f43e">
<img width="1255" alt="Screenshot 2023-09-04 at 14 16 17" src="https://github.com/conan-io/web/assets/5907894/c7bcb12e-c308-4872-b307-77f65c18f577">

**Comment by prince-chrismc** [comment]
Amazing 🔥🔥🔥
