### ISSUE TITLE
Download count on "general landing page" is not total downloads

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/web#106]
When no version is specificed in the URL, the downloads are still specific to a single version

![image](https://github.com/conan-io/web/assets/16867443/50df0f5e-d971-46c2-a4ad-45f4411d82a0)

**Comment by valgur** [comment]
The fact that the download count on the package page is for that specific version only is not really obvious either. Maybe show the total downloads in that location as well and move the per-version downloads info in the versions list view?

**Comment by franramirez688** [comment]
Hi @prince-chrismc

Yeah, that's it. The downloads are shown per version. We think it could be a bit confusing to show the total downloads even when selecting different versions. In my opinion, it should be information dedicated to each one such as the latest revision, licenses, etc.

**Comment by franramirez688** [comment]
> Maybe show the total downloads in that location as well and move the per-version downloads info in the versions list view?

Yeah, perhaps it's another good option 👍

**Comment by davidsanfal** [comment]
Hi! we've updated the number of downloads and how it is displayed.

- We show the total downloads and the current version downloads in the tabs that show the recipe information.
- We have added a new tab that shows the detailed statistics of a recipe.

<img width="1456" alt="Screenshot 2023-09-13 at 09 05 47" src="https://github.com/conan-io/web/assets/5907894/0c9028d8-a961-419f-baf4-85d7c6eacf42">

<img width="1270" alt="Screenshot 2023-09-13 at 09 03 03" src="https://github.com/conan-io/web/assets/5907894/0f25e40f-5d03-4b53-8656-1579faceaba9">

**Comment by valgur** [comment]
That's a fantastic improvement. I especially like the added OS-specific info.
Some suggestions (bordering on nitpicking, sorry):
- For the download counts, a comma for a thousands separator would make large download counts much easier to read.
- A space between the total and version download counts would be nice.
- The sidebar looks great on desktop, but on phone it feels a bit cramped. Maybe stack the info sidebar and body text instead on narrow displays.

**Comment by davidsanfal** [comment]
I'm going to take a look at it to see how we can improve it.
