### ISSUE TITLE
Provide a badge with total downloads in Conan.io

### ISSUE THREAD

**Issue by ilya-lavrenov** [conan-io/web#114]
Hi,

Currently Conan.io provides badge for the recipe https://conan.io/center/recipes/onnxruntime?version=1.15.1
But it does not provide a badge with a number of downloads. Could you please add it?

Currently, such badges are provided by brew, conda-forge, pip.

Thanks.

**Comment by ilya-lavrenov** [comment]
Hi @davidsanfal 
The ticket is closed, but I don't see a badge with a number of downloads.
Moreover, the tab with download statistic has been even removed.

Could you please clarify Conan Web UI opinion regarding it?

**Comment by davidsanfal** [comment]
@ilya-lavrenov 

You have all the info about this decision [here](https://github.com/conan-io/web/issues/128#issuecomment-1801827474)
