### ISSUE TITLE
Inconsistent information available on "Use it" page

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/web#120]
Looking at the ["Use it" page for abseil](https://conan.io/center/recipes/abseil?version=20230125.3), this is really useful - it shows the CMake targets that are available and how to use it from CMake, i.e.

```cmake
# ...
find_package(absl REQUIRED)
# ...
target_link_libraries(YOUR_TARGET abseil::abseil)
```

However, for [this is not the case for boost](https://conan.io/center/recipes/boost?version=1.83.0) - there's no CMake targets shown or how to use it from CMake at all.

I'm not sure what the technical difference between these two packages is, but we should endeavour to have consistent information shown for all packages.

As an extension to this, and perhaps this is for another ticket, it would be good to have usage instructions for all of the supported `*Deps` generators for every recipe, i.e.

* `CMakeDeps`/CMake
* `AutotoolsDeps`/Autotools
* `MakeDeps`/Makefile
* `PkgConfigDeps`/pkgconfig
* `XCodeDeps`/XCode
* `MesonToolchain`/Meson (no Deps for this?)
* `MSBuildDeps`/MSBuild
* `NMakeDeps`/NMake
* `SConsDeps`/SCons

Each of these could be a different tab on the same section providing equivalent information to what's shown above in abseil's case for CMake. Given that one of the enormous benefits of conan is the ability to abstract over the build system, demonstrating usage in each and making it easy for users to use the best build system for them would be very useful.

**Comment by franramirez688** [comment]
Hi @samuel-emrys 

Thanks for reporting it!

We're closing this issue because this one is closely related to the backend. We're still working on improving it so we hope to have all the boost targets data ready (and the rest of the missing ones) as soon as possible.

Regarding the other generator instructions, we could open another ticket to have it into account for future releases.
