### ISSUE TITLE
Confusing search results

### ISSUE THREAD

**Issue by mpusz** [conan-io/web#124]
I just noticed the search results present only the number of downloads of the latest product version, which is really confusing.

![image](https://github.com/conan-io/web/assets/506260/8c68fb5a-5415-460f-8702-8738a99dfe2a)

If I did not know that my library is better, I would probably never have chosen it, looking at the numbers. Not everybody knows that the Conan package for 2.0 was finally released yesterday, and that is why the count is so low.

Could you please provide both counts (for all downloads and for the last version) in search results so users will have a better view of each package's popularity? Or maybe just provide the total download number? I am not sure the number of downloads for the latest version is helpful on this page.

**Comment by RubenRBS** [comment]
Thanks a lot for this suggestion too, seems like a nice thing to show, because low version numbers of newly released versions can confuse the users just as you mentioned
