### ISSUE TITLE
Provide package search by tags and description contents

### ISSUE THREAD

**Issue by mpusz** [conan-io/web#125]
Right now, it seems to be impossible to find a package based on the text in its description or by trying to search for a tag associated with it.

For example, all of the following queries return empty search:
- Quantities
- #dimensional-analysis
- dimensional-analysis
- dimensional analysis

I would expect my package "mp-units" to be found in all those cases.

**Comment by RubenRBS** [comment]
Hi! Thanks for the report. We might want to improve the UX around that, but for now:
Tags need to be explicitly filtered in the topics dropdown:
![image](https://github.com/conan-io/web/assets/5364255/0d835503-98c8-415d-b686-04eeb8b2b046)

We might want to have the search match the description too, will discuss it with @davidsanfal and @franramirez688, thanks a lot for the suggestion!

**Comment by davidsanfal** [comment]
I forgot to mention that you can also search the topics using #.

<img width="1217" alt="Screenshot 2023-10-19 at 19 05 44" src="https://github.com/conan-io/web/assets/5907894/b134a1eb-e817-4881-a3d0-5a9822f6981a">
