### ISSUE TITLE
Copy button for the revision number does not work

### ISSUE THREAD

**Issue by Diesel993** [conan-io/web#127]
On for example the page for ZeroMQ 4.3.4. I saw a copy icon, to copy the revision number, but this does not work. I accessed it on Google Chrome.

**Comment by Diesel993** [comment]
I does work using Microsoft Edge

**Comment by franramirez688** [comment]
Hi @Diesel993 

Thanks for reporting the issue! 

Sadly, we could not replicate your issue. Could you specify the version of your browser where it's not working? Apart from that, to ensure the cache is not messing up anything, could you refresh your web page (`ctrl + r`) before trying the copy button again?
If it's still failing, press "(right-click mouse) -> Inspect -> Console" and let us know if you're seeing any sort of error. If yes, copy and paste here to know more details.

**Comment by Diesel993** [comment]
Thanks for the quick response. I tried again today with chrome and now it works. So not sure what went wrong. This ticket can be closed.
