### ISSUE TITLE
Download counters exaggerate downloads substantially

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/web#129]
A conan v2 compatible version of `armadillo` only made it into conan center 3 weeks ago (https://github.com/conan-io/conan-center-index/pull/19907), yet at the moment it's showing [22,176](https://conan.io/center/recipes/armadillo?version=12.6.4) current version downloads, however rarely more than 1 per day. It's obvious where the conan center CI is rebuilding the package.

![image](https://github.com/conan-io/web/assets/36361864/513211c5-2740-4a2b-b597-e48fe0baf601)

This can't be right. This is far too many downloads for this package, especially given the historical numbers don't seem to support this. Can the team look into what's causing this and rectify? Download statistics are important to understand the popularity of packages and justify support.

**Comment by samuel-emrys** [comment]
The same seems to be true of [geotrans](https://conan.io/center/recipes/geotrans?version=3.9) - single digit downloads per day, but 3200 current version downloads overall - seems suspicious

**Comment by ilya-lavrenov** [comment]
Similar issue here https://github.com/conan-io/web/issues/128
But I also wanted to differentiate CI builds against real users, which was rejected by @memsharded

**Comment by davidsanfal** [comment]
Hi! The CI that generates the packages is excluded in the data collection, these are only client calls external to our systems. anyway we will check the data in case there is something wrong. thanks for the feedback!

**Comment by samuel-emrys** [comment]
To be clear, I don't think this is related to the CI. The  above logs only show ~600 downloads of all versions, let alone the current version (which is only about 100). This is nowhere near approaching the 22,320 figure.

**Comment by davidsanfal** [comment]
We have been reviewing the source that retrieve that info and we have found the problem. In a few minutes the fix will be deployed, if you see anything else wrong let us know. We will be monitoring the data to see that everything is represented correctly. Thanks!

**Comment by samuel-emrys** [comment]
Looks like this has been fixed! Thanks.
