### ISSUE TITLE
Unable to access recipes page for libcurl

### ISSUE THREAD

**Issue by weegeekps** [conan-io/web#132]
When trying to access the recipes page for libcurl a 502 Bad Gateway error occurs with the following message:

> Error: Server Error
> The server encountered a temporary error and could not complete your request.
> 
> Please try again in 30 seconds.

Trying again has no effect, and it's been like this for at least 8 hours now. This has been tested by multiple people in different geographic locations in the US with the same result.

Link to the offending page:
https://conan.io/center/recipes/libcurl?version=8.2.1

**Comment by memsharded** [comment]
Thanks for reporting @weegeekps 

Indeed there is something weird with that page. Other pages seems to be working correctly, but libcurl isn't. I also see the error message from EU timezone, it shouldnt be a geo issue. We'll have a look as soon as possible.
