### ISSUE TITLE
[question] OpenVINO package does not show dependencies

### ISSUE THREAD

**Issue by ilya-lavrenov** [conan-io/web#133]
Hi there,

<img width="1236" alt="Screenshot 2023-11-05 at 1 30 27 AM" src="https://github.com/conan-io/web/assets/2566854/a6ace13d-f9da-422f-84c2-de7a331c3dc0">

We can see that OpenVINO package does not provide a list of dependencies, while it has multiple of them.

Could you please clarify why is it happening?

**Comment by davidsanfal** [comment]
Hello @ilya-lavrenov! after debugging our crawlers, we found a bug. it is now fixed and the information is updated. Thanks for the feedback!
