### ISSUE TITLE
Older packages show outdated revision for latest recipe

### ISSUE THREAD

**Issue by ErikTempelaarVO** [conan-io/web#138]
For example the latest revision for open62541/1.3.4 according to the website:

5985346a15abb4a0ddcc6af7de20509b

Actual conan search:
Revisions for 'open62541/1.3.4' at remote 'conan-center':
bf33cae2a791730652a100527b9b26cc (2023-09-12 08:21:14 UTC)
5985346a15abb4a0ddcc6af7de20509b (2023-01-25 10:14:18 UTC)

Same for /1.3.8

b7410a15272dd9ed4df377b49ce946be

Revisions for 'open62541/1.3.8' at remote 'conan-center':
fe187f713a2a0d5c95906129bf7d5d78 (2024-01-07 11:46:11 UTC)
b7410a15272dd9ed4df377b49ce946be (2023-11-16 10:02:06 UTC)

**Comment by davidsanfal** [comment]
we have already fixed it. thanks for your feedback!
