### ISSUE TITLE
xz_utils url err

### ISSUE THREAD

**Issue by lining1111** [conan-io/web#152]
the url xz_utils in conan is ""https://tukaani.org/xz/xz-x.x.x.tar.xz",the web site is not reachable.the new url should be "https://xz.tukaani.org/xz/xz-x.x.x.tar.xz".

**Comment by franramirez688** [comment]
Hi @lining1111 

Thanks for your report. Is your issue related to the Conan web page or the recipe itself? If you're talking about the recipe, we should transfer this issue to the  https://github.com/conan-io/conan-center-index repository then.
