### ISSUE TITLE
New Conan centre minor grammatical issue.

### ISSUE THREAD

**Issue by sizeak** [conan-io/web#153]
On the new website there is an information box:
![image](https://github.com/conan-io/web/assets/57534259/cfe3aef1-4d22-407b-85bd-1fef53ebc23c)

This is quite pedantic, but to me the first sentence uses an odd choice of words. Something like "If you are new to Conan, we recommend reading the section [how to consume packages](https://docs.conan.io/2/tutorial/consuming_packages.html)." feels much more natural, although I would suggest further refinement to something like:

"If you are a new Conan user, we recommend reading the [how to consume packages](https://docs.conan.io/2/tutorial/consuming_packages.html) tutorial."

**Comment by franramirez688** [comment]
Hi @sizeak 

Thanks for the suggestion! I agree with that 😁 
Would you like to open a pull request applying those changes?

**Comment by sizeak** [comment]
Alright, only because it's Easter Monday though 😉
