### ISSUE TITLE
[bug] Bad latest version 

### ISSUE THREAD

**Issue by franramirez688** [conan-io/web#184]
Based on https://github.com/conan-io/web/issues/187

In case of `cci.xx.x.x` and `x.x.x`, latest ones should be `x.x.x` and not the other ones.

For instance:

![Screenshot 2024-11-25 at 15 53 42](https://github.com/user-attachments/assets/637648a1-1ea3-4c3a-85ff-9c0f0c9b9f8d)
![Screenshot 2024-11-25 at 15 53 35](https://github.com/user-attachments/assets/ba95301a-2e70-4ea4-a721-87d2baac76fa)

Here, the latest one should be `0.4.0`

**Comment by davidsanfal** [comment]
is the idea to always place the cci versions after the standard ones or also taking into account also the x.y.z numbers? I suppose it is by placing the cci last, but just to confirm what is really expected

**Comment by AbrilRBS** [comment]
If it starts with cci, they should show up last yes, as Conan is sorting them "wrong".

But conversely new versions that contain cci (`1.2.cci.20240101`) can be sorted correctly by Conan so those would need no fix, but is also not s problem if they are sorted last with the other cci ones
