### ISSUE TITLE
[bug] 500 Internal Server Error https://conan.io/center

### ISSUE THREAD

**Issue by tttapa** [conan-io/web#193]
https://conan.io/center is currently not working for any package, unless a specific version is included in the URL.

To reproduce, go to https://conan.io/center and click any package from the "Popular recipes" column, such as https://conan.io/center/recipes/zlib. This results in an internal server error.

**Comment by memsharded** [comment]
Thanks very much @tttapa for reporting.

This is indeed a bug, something is broken.

While we fix it, it is possible to navigate to packages from the search box results, like https://conan.io/center/recipes/zlib?version=1.3.1 is working

**Comment by franramirez688** [comment]
@tttapa Thanks for reporting this.

It's already solved 🙏
