### ISSUE TITLE
[Search] Search bar enhancements

### ISSUE THREAD

**Issue by franramirez688** [conan-io/web#34]
* ~~Show it as enabled always~~ (done)
* ~~Add lens icon?~~ (done)
* If the search bar is on the page, let's focus on it (without needing to click there, just start typing 😁 )
* Live search (typing and showing results instead of clicking on the search button)
     * We'd need to cache all the values to speed up the global search. Now, we're performing single calls each time.
* Add a search bar to the recipe page. It'd make life easier to search for another package instead of getting back to the ConanCenter page.

**Comment by JStatnekov** [comment]
seconding this suggestion. I think having the search bar available when you navigate to a repo page is very helpful. 
For instance, on this page there is no search bar https://conan.io/center/recipes/boost?version=1.82.0

**Comment by franramirez688** [comment]
@CJCombrink @JStatnekov Thank you both for the suggestions! I just added them to the main body's issue.

**Comment by davidsanfal** [comment]
Thank you for the feedback! we are working on both features and soon they will be available on the web. in fact, the search bar on the recipe page is already being deployed. 🚀.

**Comment by davidsanfal** [comment]
@CJCombrink @JStatnekov we have already deployed both suggestions:
- searchbar at the top of each recipe page.
- autosearch after 0.5s without typing in the searchbar on the [conan.io/center/recipes](https://conan.io/center/recipes) page.
