### ISSUE TITLE
Users do not see the "Your Feedback" as a clickable link

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/web#60]
https://github.com/conan-io/web/blob/a6a4459a7111d4f44f1853fd61170e55e43ddbad/conanio/components/header.js#L35

The white text on white text with a soft bold it not obvious enough for at least 2 users

![image](https://github.com/conan-io/web/assets/16867443/f3cf9f77-8946-4c00-8285-8ccd755e5f45)

**Comment by davidsanfal** [comment]
Updated!

<img width="1028" alt="Screenshot 2023-08-01 at 14 01 45" src="https://github.com/conan-io/web/assets/5907894/f1ed9514-32e2-4ea6-a08f-9bfb5c393994">

**Comment by davidsanfal** [comment]
yes, there are small features that we are deploying from the development branches to see them faster. we are only going to do this while the web is still in beta and if the changes don't change anything critical. anyway, everything is already merged in main.
