### ISSUE TITLE
There needs to be a way to see all of the recipe versions

### ISSUE THREAD

**Issue by BoilerTom90** [conan-io/web#64]
The old UI allowed you to see all the recipe versions. That was particularly useful when builds started to break due to recipe changes and we could tell it was because of a change. Now, without that information, it's impossible to tell.

**Comment by memsharded** [comment]
I guess you mean revisions (versions are showed), so this would be a duplicated of https://github.com/conan-io/web/issues/62, thanks for reporting, lets follow up there (see comments there too)
