### ISSUE TITLE
Version order looks to be just as if sorted as strings for X.Y.Z versions where Y might have multiple digits

### ISSUE THREAD

**Issue by VladyslavOdobesku-TomTom** [conan-io/web#66]
Here is the order of versions from [vulkan-loader](https://conan.io/center/recipes/vulkan-loader) package:
1.3.204.1, 1.3.211.0, 1.2.162.0, 1.3.239.0, 1.3.236.0, 1.3.231.1, 1.3.231, 1.3.224.0, 1.3.216.0, 1.3.221, 1.3.204.0, 1.2.198.0, 1.2.190, 1.2.154.0, 1.2.189, 1.2.172, 1.2.182, 1.2.170.0.

Sorting looks gibberish.

Meanhile vulkan-headers package looks correct.

**Comment by franramirez688** [comment]
Hi @VladyslavOdobesku-TomTom 

Thanks for reporting it.
This is a known issue https://github.com/conan-io/web/issues/37 and we're working on it. We hope to have this problem solved asap.
Closing this as duplicate.
