### ISSUE TITLE
Package download counter

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/web#71]
It would be really useful to understand how much demand there is for different packages with a download counter. This helps organisations justify time spent supporting libraries and even helps us convince them to modify their behaviours to better support packaging practices. It would be good to have the following for each package:

* Lifetime (all package versions/revisions) download counter
* Version download counter

**Comment by jcar87** [comment]
Hi @samuel-emrys  - thank you for your feedback. This feature is already being worked on and current development versions of the website already display this information, this will be rolled out fairly soon. Will keep this issue open to track the work on this.

**Comment by samuel-emrys** [comment]
Can this be re-opened since this feature has since been removed? Just to track that this is still a desired feature, even if the implementation needs to be revisited
