### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by patmantru** [conan-io/web#82]
Entering the name of a package in the search box results in 0 hits...even if an exact name is specified

![image](https://github.com/conan-io/web/assets/46453397/3ab94d5d-3bf2-45b1-916c-a7da628b0d62)

**Comment by RubenRBS** [comment]
Hi @patmantru 

We were reingesting recipe data yesterday after some backend changes, seems you got unlucky and happened to search on the small update window where data is being switched around, you can try it now and it should work as expected now :)
