### ISSUE TITLE
always report unable to find xxx in remotes

### ISSUE THREAD

**Issue by zhangjinpeng66** [conan-io/web#87]
![conancenter-1](https://github.com/conan-io/web/assets/6256892/22c42184-ec6f-424a-8cd1-ab0aa2bbde69)
![conancenter-2](https://github.com/conan-io/web/assets/6256892/2a8ec1e4-52ee-442c-8cf0-4366948044b2)
![conancenter-4](https://github.com/conan-io/web/assets/6256892/f5eff8db-0d92-451e-9e68-a3a937c5df0b)
The above pictures describe the question. Please pay attention to the problem

**Comment by memsharded** [comment]
This seems duplicated reason to https://github.com/conan-io/web/issues/86#issuecomment-1685255475, using the wrong URL, please check and follow on the other ticket.
