### ISSUE TITLE
No Operating System information

### ISSUE THREAD

**Issue by acano15** [conan-io/web#90]
Comparing with the old version, the current version of the webpage no longer offers details concerning the distinct operating system prerequisites.

**Comment by davidsanfal** [comment]
Hi! we've added the available packages.

- We show the available packages in the tabs that show the recipe information.
- We have added the available packages in the search page info.

<img width="1257" alt="Screenshot 2023-09-13 at 09 15 21" src="https://github.com/conan-io/web/assets/5907894/9d842e90-1270-47a1-9ca2-53c44adc22e8">
<img width="1349" alt="Screenshot 2023-09-13 at 09 16 17" src="https://github.com/conan-io/web/assets/5907894/dbef0dd2-1451-4892-9c53-b2fe1e7ecc16">
