### ISSUE TITLE
[bug] Unable to download artifactory CE

### ISSUE THREAD

**Issue by mathieucausse** [conan-io/web#93]
### Environment details

* Windows 11, macOS

### Steps to reproduce

Click on Windows Installer from main download page
https://conan.io/downloads

returns
https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/cpp/ce/jfrog-artifactory-cpp-ce/7.63.0/jfrog-artifactory-cpp-ce-7.63.0-windows.zip

which contains

```
{
  "errors" : [ {
    "status" : 404,
    "message" : "File not found."
  } ]
}
```

**Comment by memsharded** [comment]
Transferred to the web repo

**Comment by RubenRBS** [comment]
@mathieucausse the correct URL should be https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/cpp/ce/jfrog-artifactory-cpp-ce/7.63.12/jfrog-artifactory-cpp-ce-7.63.12-windows.zip
